Terraform: add terraform config for S3 bucket and user policy
Also adds support in `script/build` to run this and `script/bootstrap`
to check for Terraform when running a build.

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -41,3 +41,15 @@ curl -L -s https://raw.github.com/mysociety/commonlib/master/bin/get_pip.bash | 
 pip install -r requirements.txt
 
 echo "==> Done setting up virtualenv."
+
+## Check for Terraform. We'll only warn here unless running a build.
+if ! command -v terraform >/dev/null 2>&1 ; then
+  if [ -n "$BUILD" ]; then
+    echo "==> Terraform not found, build aborting."
+    exit 2
+  else
+    echo "==> Warning: Terraform not found, required for build."
+  fi
+else
+  echo "==> Terraform found, OK."
+fi
